data_country = {'ANDORRA': 'AD',
                'UNITED ARAB EMIRATES': 'AE',
                'AFGHANISTAN': 'AF',
                'ANTIGUA AND BARBUDA': 'AG',
                'ANGUILLA': 'AI',
                'ALBANIA': 'AL',
                'ARMENIA': 'AM',
                'NETHERLANDS ANTILLES': 'AN',
                'ANGOLA': 'AO',
                'ARGENTINA': 'AR',
                'AMERICAN SAMOA': 'AS',
                'AUSTRIA': 'AT',
                'AUSTRALIA': 'AU',
                'ARUBA': 'AW',
                'AZERBAIJAN': 'AZ',
                'BOSNIA AND HERZEGOVINA': 'BA',
                'BARBADOS': 'BB',
                'BANGLADESH': 'BD',
                'BELGIUM': 'BE',
                'BURKINA FASO': 'BF',
                'BULGARIA': 'BG',
                'BAHRAIN': 'BH',
                'BURUNDI': 'BI',
                'BENIN': 'BJ',
                'BERMUDA': 'BM',
                'BRUNEI': 'BN',
                'BOLIVIA': 'BO',
                'Caribbean Netherlands': 'BQ',
                'BRAZIL': 'BR',
                'BAHAMAS': 'BS',
                'BHUTAN': 'BT',
                'BOUVET ISLAND': 'BV',
                'BOTSWANA': 'BW',
                'BELARUS': 'BY',
                'BELIZE': 'BZ',
                'CANADA': 'CA',
                'COCOS(KEELING)ISLANDS': 'CC',
                'CONGO REPUBLIC': 'CD',
                'CENTRAL REPUBLIC': 'CF',
                'CONGO': 'CG',
                'SWITZERLAND': 'CH',
                'COTE D&#039;LVOIRE(IVORY)': 'CI',
                'COOK ISLANDS': 'CK',
                'CHILE': 'CL',
                'CAMEROON': 'CM',
                'CHINA': 'CN',
                'COLOMBIA': 'CO',
                'COSTA RICA': 'CR',
                'CUBA': 'CU',
                'CAPE VERDE': 'CV',
                'CHRISTMAS ISLAND': 'CX',
                'CYPRUS': 'CY',
                'CZECH REPUBLIC': 'CZ',
                'GERMANY': 'DE',
                'DJIBOUTI': 'DJ',
                'DENMARK': 'DK',
                'DOMINICA': 'DM',
                'DOMINICAN REPUBLIC': 'DO',
                'ALGERIA': 'DZ',
                'ECUADOR': 'EC',
                'ESTONIA': 'EE',
                'EGYPT': 'EG',
                'WESTERN SAHARA': 'EH',
                'ERITREA': 'ER',
                'SPAIN': 'ES',
                'ETHIOPIA': 'ET',
                'FINLAND': 'FI',
                'FIJI': 'FJ',
                'FALKLAND ISLAND': 'FK',
                'MICRONESIA': 'FM',
                'FAROE ISLANDS': 'FO',
                'FRANCE': 'FR',
                'FRANCE, METROPOLITAN': 'FX',
                'GABON': 'GA',
                'UNITED KINGDOM': 'GB',
                'GRENADA': 'GD',
                'GEORGIA': 'GE',
                'FRENCH GUIANA': 'GF',
                'GUERNSEY': 'GG',
                'GHANA': 'GH',
                'GIBRALTAR': 'GI',
                'GREENLAND': 'GL',
                'GAMBIA': 'GM',
                'GUINEA': 'GN',
                'GUADELOUPE': 'GP',
                'EQUATORIAL GUINEA': 'GQ',
                'GREECE': 'GR',
                'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL': 'GS',
                'GUATEMALA': 'GT',
                'GUAM': 'GU',
                'GUINEA BISSAU': 'GW',
                'GUYANA (BRITISH)': 'GY',
                'HONG KONG': 'HK',
                'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
                'HONDURAS': 'HN',
                'CROATIA': 'HR',
                'HAITI': 'HT',
                'HUNGARY': 'HU',
                'CANARY ISLANDS': 'IC',
                'INDONESIA': 'ID',
                'IRELAND': 'IE',
                'ISRAEL': 'IL',
                'INDIA': 'IN',
                'BRITISH INDIAN OCEAN TERRITORY': 'IO',
                'IRAQ': 'IQ',
                'IRAN (ISLAMIC REPUBLIC OF)': 'IR',
                'ICELAND': 'IS',
                'ITALY': 'IT',
                'JERSEY': 'JE',
                'JAMAICA': 'JM',
                'JORDAN': 'JO',
                'JAPAN': 'JP',
                'YUGOSLAVIA': 'JU',
                'KENYA': 'KE',
                'KYRGYZSTAN': 'KG',
                'CAMBODIA': 'KH',
                'KIRIBATI REPUBILC': 'KI',
                'COMOROS': 'KM',
                'SAINT KITTS': 'KN',
                'NORTH KOREA': 'KP',
                'SOUTH KOREA': 'KR',
                'KOSOVO': 'KV',
                'KUWAIT': 'KW',
                'CAYMAN ISLANDS': 'KY',
                'KAZAKHSTAN': 'KZ',
                'LAOS': 'LA',
                'LEBANON': 'LB',
                'ST. LUCIA': 'LC',
                'LIECHTENSTEIN': 'LI',
                'SRI LANKA': 'LK',
                'LIBERIA': 'LR',
                'LESOTHO': 'LS',
                'LITHUANIA': 'LT',
                'LUXEMBOURG': 'LU',
                'LATVIA': 'LV',
                'LIBYA': 'LY',
                'MOROCCO': 'MA',
                'MONACO': 'MC',
                'MOLDOVA': 'MD',
                'MONTENEGRO': 'ME',
                'MADAGASCAR': 'MG',
                'MARSHALL ISLANDS': 'MH',
                'MACEDONIA': 'MK',
                'MALI': 'ML',
                'MYANMAR': 'MM',
                'MONGOLIA': 'MN',
                'MACAU': 'MO',
                'SAIPAN': 'MP',
                'MARTINIQUE': 'MQ',
                'MAURITANIA': 'MR',
                'MONTSERRAT': 'MS',
                'Malta': 'MT',
                'MAURITIUS': 'MU',
                'MALDIVES': 'MV',
                'MALAWI': 'MW',
                'MEXICO': 'MX',
                'MALAYSIA': 'MY',
                'MOZAMBIQUE': 'MZ',
                'NAMIBIA': 'NA',
                'NEW CALEDONIA': 'NC',
                'NIGER': 'NE',
                'NORFOLK ISLAND': 'NF',
                'NIGERIA': 'NG',
                'NICARAGUA': 'NI',
                'NETHERLANDS': 'NL',
                'NORWAY': 'NO',
                'NEPAL': 'NP',
                'NAURU REPUBLIC': 'NR',
                'NIUE': 'NU',
                'NEW ZEALAND': 'NZ',
                'OMAN': 'OM',
                'PANAMA': 'PA',
                'PERU': 'PE',
                'FRENCH POLYNESIA': 'PF',
                'PAPUA NEW GUINEA': 'PG',
                'PHILIPPINES': 'PH',
                'PAKISTAN': 'PK',
                'POLAND': 'PL',
                'SAINT PIERRE AND MIQUELON': 'PM',
                'PITCAIRN ISLANDS': 'PN',
                'PUERTO RICO': 'PR',
                'PORTUGAL': 'PT',
                'PALAU': 'PW',
                'PARAGUAY': 'PY',
                'QATAR': 'QA',
                'REUNION ISLAND': 'RE',
                'ROMANIA': 'RO',
                'SERBIA, REPUBLIC OF': 'RS',
                'RUSSIA': 'RU',
                'RWANDA': 'RW',
                'SAUDI ARABIA': 'SA',
                'SOLOMON ISLANDS': 'SB',
                'SEYCHELLES': 'SC',
                'SUDAN': 'SD',
                'SWEDEN': 'SE',
                'SINGAPORE': 'SG',
                'ST HELENA': 'SH',
                'SLOVENIA': 'SI',
                'SVALBARD AND JAN MAYEN': 'SJ',
                'SLOVAKIA REPUBLIC': 'SK',
                'SIERRA LEONE': 'SL',
                'SAN MARINO': 'SM',
                'SENEGAL': 'SN',
                'SOMALIA': 'SO',
                'SURINAME': 'SR',
                'SOUTH SUDAN': 'SS',
                'SAO TOME AND PRINCIPE': 'ST',
                'EL SALVADOR': 'SV',
                'SYRIA': 'SY',
                'SWAZILAND': 'SZ',
                'TRISTAN DA CUNBA': 'TA',
                'TURKS AND CAICOS ISLANDS': 'TC',
                'CHAD': 'TD',
                'FRENCH SOUTHERN TERRITORIES': 'TF',
                'TOGO': 'TG',
                'THAILAND': 'TH',
                'TAJIKISTAN': 'TJ',
                'TOKELAU': 'TK',
                'EAST TIMOR': 'TL',
                'TURKMENISTAN': 'TM',
                'TUNISIA': 'TN',
                'TONGA': 'TO',
                'TURKEY': 'TR',
                'TRINIDAD AND TOBAGO': 'TT',
                'TUVALU': 'TV',
                'TAIWAN': 'TW',
                'TANZANIA': 'TZ',
                'UKRAINE': 'UA',
                'UGANDA': 'UG',
                'UNITED STATES MINOR OUTLYING ISLANDS': 'UM',
                'UNITED STATES': 'US',
                'URUGUAY': 'UY',
                'UZBEKISTAN': 'UZ',
                'VATICAN CITY': 'VA',
                'SAINT VINCENT AND THE GRENADINES': 'VC',
                'VENEZUELA': 'VE',
                'VIRGIN ISLAND (GB)': 'VG',
                'VIRGIN ISLAND (US)': 'VI',
                'VIETNAM': 'VN',
                'VANUATU': 'VU',
                'WALLIS AND FUTUNA ISLANDS': 'WF',
                'WESTERN SAMOA': 'WS',
                'BONAIRE': 'XB',
                'CURACAO': 'XC',
                'ASCENSION': 'XD',
                'ST. EUSTATIUS': 'XE',
                'SPANISH TERRITORIES OF N.AFRICA': 'XG',
                'AZORES': 'XH',
                'MADEIRA': 'XI',
                'BALEARIC ISLANDS': 'XJ',
                'CAROLINE ISLANDS': 'XK',
                'ST. MAARTEN': 'XM',
                'NEVIS': 'XN',
                'SOMALILAND': 'XS',
                'ST. BARTHELEMY': 'XY',
                'YEMEN, REPUBLIC OF': 'YE',
                'MAYOTTE': 'YT',
                'SOUTH AFRICA': 'ZA',
                'ZAMBIA': 'ZM',
                'ZAIRE': 'ZR',
                'ZIMBABWE': 'ZW',
                'DEUTSCHLAND': 'DE',
                'ÖSTERREICH': 'AT',
                }
word_number = ['', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
               'U', 'V', 'W', 'X', 'Y', 'Z']
champion_name = ['Tankstelle', 'KG', 'Inc.', 'Co.', 'Co', 'Ltd.', 'SDN', 'BHD', 'GmbH', 'AG', 'S.A.', 'SA',
                 'S.A.R.L.', 'B.V.', 'N.V.', 'A/S', 'S.P.A.', 'S.R.L.', 'PLC',
                 'AB', 'OY', 'S.L.', 'Gmbh', 'C/o', 'Konzeption', 'dreimalacht', 'Schreinerei', 'Ltd', 'Schnabuleum',
                 'Consulting',
                 'Mediengestaltung', 'Konstanz', 'Ug', 'ICT', 'Börde', 'CHAUSSEE', 'SAS', 'INSIDIX', 'e.U.', 'Schübel',
                 'c/o', 'Coworking', 'Office', 'Ingo', 'Andreas', 'IT', 'Immulab', 'SIGNAL', 'Wilk', 'DATAMIN',
                 'e.K.', 'e.V.', 'GbR', 'mbh', 'Co KG', 'privat', 'apotheke', 'appt', 'OG', 'EG', 'LINKS', 'Rechts',
                 'Kreuz', 'Gang', 'Gebäude', 'Stock', 'co', 'C/O']
new_columns = ['参考编号/Reference Code', '收件人姓名/Consignee Name', '收件人国家/Consignee Country', '城市/City',
               '街道/Street', '邮编/Zip Code', '收件人电话/Consignee Phone', 'SKU1', '数量1/Quantity 1',
               '门牌号/Doorplate', '收件人Email/Consignee Email', '收件人公司/Consignee Company']
ez_street = {
    'TRASSE': 'tr.',
    'traße': 'tr',
    'VENUE': 've',
    'ÂTIMENT': 'ât',
    'PPARTEMENT': 'pt'
}
name_list = ['自动分配仓库', '仓库代码/Warehouse Code', '参考编号/Reference Code',
             '派送方式/Delivery Style', '销售平台/Sales Platform', '跟踪号/Tracking number',
             '订单成本价/total_amount_excl_vat', '订单交易额/total_amount_incl_vat',
             'COD订单/COD Orders', 'COD Value', '币种/Currency', '年龄/Age',
             '收件人姓名/Consignee Name', '收件人公司/Consignee Company',
             '收件人国家/Consignee Country', '州/Province', '区/District', '城市/City',
             '街道/Street', '街道2/Street2', '街道3/Street3', '门牌号/Doorplate',
             '邮编/Zip Code', '收件人Email/Consignee Email', '收件人电话/Consignee Phone',
             '收件人电话2/Consignee Phone2', '收件人证件号/Consignee License', '备注/Remark',
             'SKU1', '数量1/Quantity 1', '英文申报名称/Product Name En 1',
             '申报价值/Declared Value 1', 'SKU2', '数量2/Quantity 2',
             '英文申报名称/Product Name En 2', '申报价值/Declared Value 2', 'SKU3',
             '数量3/Quantity 3', '英文申报名称/Product Name En 3', '申报价值/Declared Value 3',
             'SKU4', '数量4/Quantity 4', '英文申报名称/Product Name En 4',
             '申报价值/Declared Value 4', 'SKU5', '数量5/Quantity 5',
             '英文申报名称/Product Name En 5', '申报价值/Declared Value 5', 'SKU6',
             '数量6/Quantity 6', '英文申报名称/Product Name En 6', '申报价值/Declared Value 6',
             'SKU7', '数量7/Quantity 7', '英文申报名称/Product Name En 7',
             '申报价值/Declared Value 7', 'SKU8', '数量8/Quantity 8',
             '英文申报名称/Product Name En 8', '申报价值/Declared Value 8', 'SKU9',
             '数量9/Quantity 9', '英文申报名称/Product Name En 9', '申报价值/Declared Value 9',
             'SKU10', '数量10/Quantity 10', '英文申报名称/Product Name En 10',
             '申报价值/Declared Value 10', '保险服务/Insurance', '投保金额/Insurance Amount',
             '签名服务/Signature', '平台店铺/Platform Shop', '买家ID/Buyers Id',
             '是否强制放货/Mandatory Release Cargo', '订单类型/Order Kind',
             '订购人/Order Payer Name', '订购人证件号/Order Id Number',
             '订购人电话/Order Payer Phone', '原产国/Order Country Code Origin',
             '订单销售金额/Order Sales Amount', '订单销售金额币种/Order Sales Currency',
             '是否ebay平台/Is Platform Ebay', 'ebay平台交易id/Ebay Item Id',
             'ebay平台交易号/Ebay Transaction Id', '税金付款方式/Tax Payment Method',
             'VAT税号/Vat Tax Code', '配货信息/Distribution Information',
             '收件人税号类型/Consignee Tax Type', '配送指定日期/Assign Send Date',
             '配送指定时间/Assign Send Time']
